version: '3.4'

services:
  tripweather:
    image: tripweather
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:3005 --nothreading --noreload"]
    ports:
      - 3005:3005
      - 5678:5678
