# Generated by Django 5.1.1 on 2024-09-08 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripResultReturnApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityweatherinfo',
            name='temperature',
        ),
        migrations.AddField(
            model_name='cityweatherinfo',
            name='country',
            field=models.CharField(default='United State', max_length=128),
        ),
        migrations.AddField(
            model_name='cityweatherinfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 11, 15, 5, 539359)),
        ),
        migrations.AddField(
            model_name='cityweatherinfo',
            name='max_temperature',
            field=models.FloatField(default=200.0),
        ),
        migrations.AddField(
            model_name='cityweatherinfo',
            name='min_temperature',
            field=models.FloatField(default=200.0),
        ),
        migrations.AddField(
            model_name='cityweatherinfo',
            name='prec_hours',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='cityweatherinfo',
            name='prec_prob_max',
            field=models.FloatField(default=200.0),
        ),
        migrations.AddField(
            model_name='cityweatherinfo',
            name='prec_prob_mean',
            field=models.FloatField(default=200.0),
        ),
        migrations.AddField(
            model_name='cityweatherinfo',
            name='prec_prob_min',
            field=models.FloatField(default=200.0),
        ),
        migrations.AddField(
            model_name='cityweatherinfo',
            name='rain',
            field=models.FloatField(default=200.0),
        ),
        migrations.AddField(
            model_name='cityweatherinfo',
            name='showers',
            field=models.FloatField(default=200.0),
        ),
        migrations.AddField(
            model_name='cityweatherinfo',
            name='snow',
            field=models.FloatField(default=200.0),
        ),
        migrations.AddField(
            model_name='cityweatherinfo',
            name='trip',
            field=models.CharField(default='Misc', max_length=128),
        ),
        migrations.AddField(
            model_name='cityweatherinfo',
            name='uv_index_max',
            field=models.FloatField(default=200.0),
        ),
        migrations.AddField(
            model_name='cityweatherinfo',
            name='wind_speed_max',
            field=models.FloatField(default=200.0),
        ),
        migrations.AlterField(
            model_name='cityweatherinfo',
            name='city',
            field=models.CharField(default='New York', max_length=128),
        ),
        migrations.AlterField(
            model_name='cityweatherinfo',
            name='precipitation',
            field=models.FloatField(default=200.0),
        ),
    ]
