# Generated by Django 5.1.1 on 2024-09-08 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripResultReturnApi', '0002_remove_cityweatherinfo_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityweatherinfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 13, 48, 10, 703911)),
        ),
    ]
