# Generated by Django 5.1.1 on 2024-09-08 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripResultReturnApi', '0005_alter_cityweatherinfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityweatherinfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 23, 53, 53, 879522)),
        ),
    ]
